apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: proxy-dckn
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/rh-ee-abarbaro-tenant/proxy/proxy-dckn@sha256:eb282c3c42edbf8a1be9339a2168bb601bb06110cfcee9bedc4de5bfe69bacd6
        name: container-image
        resources: {}
status: {}
