apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: proxy-dckn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: proxy-dckn
    app.kubernetes.io/part-of: proxy
  name: proxy-dckn
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: proxy-dckn
status:
  loadBalancer: {}
